[[admin.config.cookies]]
== Cookies

$g_cookie_path::
  Specifies the path under which a cookie is visible.
  +
  All scripts in this directory and its sub-directories will be able to
  access MantisBT cookies.
  +
  Default value is '/'. It is recommended to set this to the actual
  MantisBT path.
$g_cookie_domain::
  The domain that the MantisBT cookies are available to.
$g_cookie_prefix::
  Prefix for all MantisBT cookies
  +
  This should be an identifier which does not include spaces or periods,
  and should be unique per MantisBT installation, especially if
  $g_cookie_path is not restricting the cookies' scope to the actual
  MantisBT directory.
  +
  It applies to the cookies listed below. Their actual names are
  calculated by prepending the prefix, and it is not expected for the
  user to need to change these.
  +
  * $g_string_cookie
  * $g_project_cookie
  * $g_view_all_cookie
  * $g_manage_users_cookie
  +
  Stores the filter criteria for the Manage Users page
  * $g_manage_config_cookie
  +
  Stores the filter criteria for the Manage Config Report page
  * $g_logout_cookie
  * $g_bug_list_cookie
