[[admin.config.duedate]]
== Due Date

$g_due_date_update_threshold::
  Threshold to update due date submitted. Default is NOBODY.
$g_due_date_view_threshold::
  Threshold to see due date. Default is NOBODY.
$g_due_date_default::
  Default due date value for newly submitted issues: Empty string for no
  due date set. Related date that is accepted by
  https://www.php.net/manual/en/function.strtotime.php[strtotime()],
  e.g. 'today' or '+2 days'. Default is ''.
$g_due_date_warning_levels::
  Due date warning levels. A variable number of Levels (defined as a
  number of seconds going backwards from the current timestamp, compared
  to an issue's due date) can be defined. Levels must be defined in
  ascending order.
  +
  * The first entry (array key 0) defines _Overdue_. Normally and by
  default, its value is `0`, meaning that issues will be marked overdue
  as soon as their due date has passed. However, it is also possible to
  set it to a higher value to flag overdue issues earlier, or even use a
  negative value to allow a "grace period" after due date.
  * Array keys 1 and 2 offer two levels of _Due soon_: orange and green.
  By default, only the first one is set, to 7 days.
  +
  Out of the box, MantisBT allows for 3 warning levels. Additional ones
  may be defined, but in that case new `due-N` CSS rules (where N is the
  array's index) must be created otherwise the extra levels will not be
  highlighted in the UI.
