[[admin.config.fields]]
== Field Visibility

$g_enable_eta::
  Enable or disable usage of 'ETA' field. Default value is OFF.
$g_enable_projection::
  Enable or disable usage of 'Projection' field. Default value is OFF.
$g_enable_product_build::
  Enable or disable usage of 'Product Build' field. Default is OFF.
$g_bug_report_page_fields::
  An array of optional fields to show on the bug report page.
  +
  The following optional fields are allowed: additional_info,
  attachments, category_id, due_date, handler, monitors, os, os_build,
  platform, priority, product_build, product_version, reproducibility,
  resolution, severity, status, steps_to_reproduce, tags,
  target_version, view_state.
  +
  The summary and description fields are always shown and do not need to
  be listed in this option. Fields not listed above cannot be shown on
  the bug report page. Visibility of custom fields is handled via the
  Manage => Manage Custom Fields administrator page.
  +
  Note that _monitors_ is not an actual field; adding it to the list
  will let authorized reporters (see _monitor_add_others_bug_threshold_
  in link:#admin.config.misc[???]) select users to add to the issue's
  monitoring list. Monitors will only be notified of the submission if
  both their e-mail preferencess and the _notify_flags_ configuration
  (see link:#admin.config.email[???]) allows it, i.e.
  +
....
$g_notify_flags['new']['monitor'] = ON;
....
  +
  This setting can be set on a per-project basis by using the Manage =>
  Manage Configuration administrator page.
$g_bug_view_page_fields::
  An array of optional fields to show on the issue view page and other
  pages that include issue details.
  +
  The following optional fields are allowed: additional_info,
  attachments, category_id, date_submitted, description, due_date, eta,
  fixed_in_version, handler, id, last_updated, os, os_build, platform,
  priority, product_build, product_version, project, projection,
  reporter, reproducibility, resolution, severity, status,
  steps_to_reproduce, summary, tags, target_version, view_state.
  +
  Fields not listed above cannot be shown on the bug view page.
  Visibility of custom fields is handled via the Manage => Manage Custom
  Fields administrator page.
  +
  This setting can be set on a per-project basis by using the Manage =>
  Manage Configuration administrator page.
$g_bug_update_page_fields::
  An array of optional fields to show on the bug update page.
  +
  The following optional fields are allowed: additional_info,
  category_id, date_submitted, description, due_date, eta,
  fixed_in_version, handler, id, last_updated, os, os_build, platform,
  priority, product_build, product_version, project, projection,
  reporter, reproducibility, resolution, severity, status,
  steps_to_reproduce, summary, target_version, view_state.
  +
  Fields not listed above cannot be shown on the bug update page.
  Visibility of custom fields is handled via the Manage => Manage Custom
  Fields administrator page.
  +
  This setting can be set on a per-project basis by using the Manage =>
  Manage Configuration administrator page.
