[[admin.config.filters]]
== Filters

$g_filter_by_custom_fields::
  Show custom fields in the filter dialog and use these in filtering.
  Defaults to ON.
$g_filter_custom_fields_per_row::
  The number of filter fields to display per row. The default is 8.
$g_view_filters = SIMPLE_DEFAULT;::
  Controls the display of the filter pages. Possible values are:
  +
  * SIMPLE_ONLY - only allow use of simple view
  * ADVANCED_ONLY - only allow use of advanced view (allows multiple
  value selections)
  * SIMPLE_DEFAULT - defaults to simple view, but shows a link for
  advanced
  * ADVANCED_DEFAULT - defaults to advanced view, but shows a link for
  simple
$g_use_dynamic_filters = ON;::
  This switch enables the use of AJAX to dynamically load and create
  filter form controls upon request. This method will reduce the amount
  of data that needs to be transferred upon each page load dealing with
  filters and thus will result in speed improvements and bandwidth
  reduction.
$g_create_permalink_threshold::
  The threshold required for users to be able to create permalinks
  (default DEVELOPER). To turn this feature off use NOBODY.
$g_create_short_url::
  The service to use to create a short URL. The %s will be replaced by
  the long URL. By default https://www.tinyurl service is used to
  shorten URLs.
