[[admin.config.misc]]
== Misc

$g_user_login_valid_regex::
  The regular expression to use when validating new user login names.
  The default regular expression allows a-z, A-Z, 0-9, +, -, dot, space
  and underscore. If you change this, you may want to update the
  ERROR_USER_NAME_INVALID string in the language files to explain the
  rules you are using on your site.
  +
  See https://en.wikipedia.org/wiki/Regular_Expression[Wikipedia] for
  more details about regular expressions. For testing regular
  expressions, use https://rubular.com/[Rubular].
$g_monitor_bug_threshold::
  Access level needed to monitor issues. The default value is REPORTER.
$g_show_monitor_list_threshold::
  Access level needed to show the list of users monitoring an issue. The
  default value is DEVELOPER.
$g_monitor_add_others_bug_threshold::
  Access level needed to add other users to the list of users monitoring
  an issue. The default value is DEVELOPER.
  +
  This setting should not be lower than
  _$g_show_monitor_list_threshold_.
$g_monitor_delete_others_bug_threshold::
  Access level needed to delete other users from the list of users
  monitoring an issue. The default value is DEVELOPER.
  +
  This setting should not be lower than
  _$g_show_monitor_list_threshold_.
$g_allow_reporter_close::
  Allow reporters to close the bugs they reported.
$g_delete_bug_threshold::
  Allow the specified access level and above to delete bugs.
$g_bug_move_access_level::
  Allow the specified access level and above to move bugs between
  projects.
$g_allow_account_delete::
  Allow users to delete their own accounts.
$g_allow_anonymous_login::
  Enable anonymous access to Mantis. You must also specify
  $g_anonymous_account as the account which anonymous users will browse
  Mantis with. The default setting is OFF.
$g_anonymous_account::
  Define the account which anonymous users will assume when using
  Mantis. This account is considered by Mantis to be protected from
  modification. In other words, this account can only be modified by
  users with an access level equal to or higher than
  $g_manage_user_threshold. Anonymous users will not be able to adjust
  preferences or change account settings like normal users can.
  +
  You will need to create a new account to use for this
  $g_anonymous_account setting. When creating the account you should
  specify a password, email address and so forth in the same way you'd
  create any other account. It is suggested that the access level for
  this account be set to VIEWER or some other read only level.
  +
  The anonymous user account will not receive standard notifications and
  can not monitor issues.
  +
  The default setting is blank/undefined. You only need to define this
  setting when $g_allow_anonymous_login is set to ON.
$g_bug_link_tag::
  If a number follows this tag it will create a link to a bug. Default
  is '#'.
  +
  * '#': a link would be #45
  * 'bug:' a link would be bug:98
$g_bugnote_link_tag::
  If a number follows this tag it will create a link to a bug note.
  Default is '~'.
  +
  * '~': a link would be ~45
  * 'bugnote:' a link would be bugnote:98
$g_enable_project_documentation::
  Specifies whether to enable support for project documents or not.
  Default is OFF. This feature is deprecated and is expected to be moved
  to a plugin in the future.
$g_admin_site_threshold::
  Threshold at which a user is considered to be a site administrator.
  These users have the highest level of access to your Mantis
  installation. This access level is required to change key Mantis
  settings (such as server paths) and perform other administrative
  duties. You may need to change this value from the default of
  ADMINISTRATOR if you have defined a new access level to replace the
  default ADMINISTRATOR level in constant_inc.php.
  +
  [WARNING]
  ====
  This is a potentially dangerous configuration option. Users at or
  above this threshold value will have permission to all aspects of
  Mantis including the admin/ directory. With this access level, users
  can damage your installation of Mantis, destroy your database or have
  elevated access to your server.

  DO NOT CHANGE THIS VALUE UNLESS YOU ABSOLUTELY KNOW WHAT YOU'RE DOING.
  BE VERY CAREFUL WITH CHANGING THIS CONFIGURATION VALUE FROM THE
  DEFAULT SETTING.
  ====
$g_manage_configuration_threshold::
  The threshold required for users to be able to manage configuration of
  a project. This includes workflow, email notifications, columns to
  view, and others. Default is MANAGER.
$g_view_configuration_threshold::
  Threshold for users to view the raw system configurations as stored in
  the database. The default value is ADMINISTRATOR.
$g_set_configuration_threshold::
  Threshold for users to set the system configurations generically via
  MantisBT web interface. The default value is ADMINISTRATOR.
  +
  [WARNING]
  ====
  Users who have access to set configuration via the interface MUST be
  trusted. This is due to the fact that these users can leverage the
  interface to _inject PHP code_ into the system, which is a potential
  security risk.
  ====
