[[admin.config.path]]
== Path

These path settings are important for proper linking within MantisBT. In
most scenarios the default values should work fine, and you should not
need to override them.

$g_path::
  URL to your installation as seen from the web browser; this is what
  you type into the URL field. Requires trailing '/' character. eg.
  'https://www.example.com/mantisbt/'. MantisBT will default this to the
  correct value. However, in some cases it might be necessary to
  override the default. This is typically needed when an installation
  can be accessed by multiple URLs (internal vs external).
$g_short_path::
  Short web path without the domain name. This requires the trailing
  '/'.
$g_absolute_path::
  This is the absolute file system path to the MantisBT installation, it
  is defaulted to the directory where config_defaults_inc.php resides.
  Requires trailing '/' character (eg. '/usr/apache/htdocs/mantisbt/').
$g_core_path::
  This is the path to the core directory of your installation. The
  default value is usually OK but it is recommended that you move the
  'core' directory out of your webroot. Requires trailing
  DIRECTORY_SEPARATOR character.
$g_class_path::
  This is the path to the classes directory which is a sub-directory of
  core by default. The default value is typically OK. Requires trailing
  DIRECTORY_SEPARATOR. character.
$g_library_path::
  This is the path to the library directory of your installation. The
  default value is usually OK but it is recommended that you move the
  'library' directory out of your webroot. Requires trailing
  DIRECTORY_SEPARATOR character.
$g_language_path::
  This is the path to the language directory of your installation. The
  default value is usually OK but it is recommended that you move the
  'language' directory out of your webroot. Requires trailing
  DIRECTORY_SEPARATOR character.
$g_manual_url::
  This is the url to the MantisBT online manual. Requires trailing '/'
  character.
