[[admin.config.relationship]]
== Relationship Graphs

MantisBT can display a graphical representation of the relationships
between issues. Two types of interactive visualizations are available,
_dependencies_ and a full _relationships_ graph.

[IMPORTANT]
====
This feature relies on the external _dot_ and _neato_ tools from the
https://www.graphviz.org/[GraphViz] library, which must be installed
separately.

Most Linux distributions have a GraphViz package available for easy
download and install.

Under Windows, the software needs to be installed manually. The
following post-installation steps
https://mantisbt.org/bugs/view.php?id=27584#c64693[may be required] for
proper operations:

* Update the system PATH to point to GraphViz's `bin` directory
* Initialize the graph engine by running `dot -c` from an
_Administrator_ command prompt.
====

$g_relationship_graph_enable::
  This enables the relationship graphs feature where issues are
  represented by nodes and relationships as links between such nodes.
  Possible values are ON or OFF. Default is OFF.
$g_relationship_graph_fontname::
  Font name and size, as required by Graphviz. If Graphviz fails to run
  for you, you are probably using a font name that gd PHP extension
  can't find. On Linux, try the name of the font file without the
  extension. The default value is 'Arial'.
$g_relationship_graph_fontsize::
  Font size, default is 8.
$g_relationship_graph_orientation::
  Default dependency orientation. If you have issues with lots of
  children or parents, leave as 'horizontal', otherwise, if you have
  lots of "chained" issue dependencies, change to 'vertical'. Default is
  'horizontal'.
$g_relationship_graph_max_depth::
  Max depth for relation graphs. This only affects relationship graphs,
  dependency graphs are drawn to the full depth. The default value is 2.
$g_relationship_graph_view_on_click::
  If set to ON, clicking on an issue on the relationship graph will open
  the bug view page for that issue, otherwise, will navigate to the
  relationship graph for that issue.
$g_dot_tool::
  The full path for the dot tool. The webserver must have execute
  permission to this program in order to generate relationship graphs.
  This configuration option is not relevant for Windows. The default
  value is '/usr/bin/dot'.
$g_neato_tool::
  The full path for the neato tool. The webserver must have execute
  permission to this program in order to generate relationship graphs.
  This configuration option is not relevant for Windows. The default
  value is '/usr/bin/neato'.
