[[admin.config.reminders]]
== Reminders

Sending reminders is a feature where a user can notify / remind other
users about a bug. In the past, only selected users like the managers,
or developers would get notified about bugs. However, these people can
not invite other people (through MantisBT) to look at or monitor these
bugs.

This feature is useful if the Manager needs to get feedback from testers
/ requirements team about a certain bug. It avoid needing this person to
do this manual outside MantisBT. It also records the history of such
reminders.

$g_store_reminders::
  Specifies if reminders should be stored as bugnotes. The bugnote will
  still reflect that it is a reminder and list the names of users that
  got it. Default is ON.
$g_reminder_recipients_monitor_bug::
  Specifies if users who receive reminders about a bug, should be
  automatically added to the monitor list of that bug. Default is ON.
$g_mentions_enabled::
  Enables or disables the @ mentions feature. Default is ON. When a user
  is @ mentioned in an issue or a note, they receive an email
  notification to get their attention. Users can be @ mentioned using
  their username and not realname.
  +
  This feature works with fields like summary, description, additional
  info, steps to reproduce and notes.
$g_mentions_tag::
  The tag to use for prefixing mentions. Default is '@'.
