[[admin.config.signup]]
== Signup and Lost Password

$g_allow_signup::
  Allow users to signup for their own accounts.
  +
  If ON (default), then $g_send_reset_password must be ON as well, and
  mail settings must be correctly configured (see
  link:#admin.config.email[???]).
$g_max_failed_login_count::
  Maximum number of failed login attempts before the user's account is
  locked. Once locked, it is required to reset the password (lost
  password). The counter is reset to zero after each successful login.
  +
  Default is set to 5, in order to prevent brute force attacks
  attempting to gain access to end users accounts. Set to OFF to disable
  this feature and allow unlimited failed login attempts.
$g_notify_new_user_created_threshold_min::
  The minimum global access level required to be notified when a new
  user registers via the "signup form". To pick specific access levels
  that are not necessarily at the higher end of access levels, use an
  array of access levels. Default is ADMINISTRATOR.
$g_send_reset_password::
  If ON (default), users will be sent their password when their account
  is created or password reset (this requires mail settings to be
  correctly configured).
  +
  If OFF, then the Administrator will have to provide a password when
  creating new accounts, and the password will be set to blank when
  reset.
$g_signup_use_captcha::
  TODO
$g_system_font_folder::
  TODO
$g_lost_password_feature::
  TODO
$g_max_lost_password_in_progress_count::
  TODO
