[[admin.config.status]]
== Status Settings

$g_bug_submit_status::
  Status to assign to the bug when submitted. Default value is NEW_.
$g_bug_assigned_status::
  Status to assign to the bug when assigned. Default value is ASSIGNED.
$g_bug_reopen_status::
  Status to assign to the bug when reopened. Default value is FEEDBACK.
$g_bug_feedback_status::
  Status to assign to the bug when feedback is required from the issue
  reporter. Once the reporter adds a note the status moves back from
  feedback to $g_bug_assigned_status or $g_bug_submit_status based on
  whether the bug assigned or not.
$g_reassign_on_feedback::
  When a note is added to a bug currently in $g_bug_feedback_status, and
  the note author is the bug's reporter, this option will automatically
  set the bug status to $g_bug_submit_status or $g_bug_assigned_status
  if the bug is assigned to a developer. Default value is ON.
$g_bug_duplicate_resolution::
  Default resolution to assign to a bug when it is resolved as being a
  duplicate of another issue. Default value is DUPLICATE.
$g_bug_reopen_resolution::
  Resolution to assign to the bug when reopened. Default value is
  REOPENED.
$g_auto_set_status_to_assigned::
  Automatically set status to $g_bug_assigned_status whenever a bug is
  assigned to a person. Installations where assigned status is to be
  used when the defect is in progress, rather than just put in a
  person's queue should set it to OFF. Default is ON. For the status
  change to be effective, these conditions must be met:
  +
  * Bug has no handler, and a new handler is selected
  * The assignment is not part of a explicit status change
  * Current bug status is lower than defined "assigned" status
  * "Assigned" status is reachable by workflow configuration
  +
  If the conditions are not met, the assignment is still made, but
  status will not be modified.
$g_bug_resolved_status_threshold::
  Bug is resolved, ready to be closed or reopened. In some custom
  installations a bug maybe considered as resolved when it is moved to a
  custom (FIXED OR TESTED) status.
$g_bug_resolution_fixed_threshold::
  Threshold resolution which denotes that a bug has been resolved and
  successfully fixed by developers. Resolutions above and including this
  threshold and below $g_bug_resolution_not_fixed_threshold are
  considered to be resolved successfully. Default value is FIXED.
$g_bug_resolution_not_fixed_threshold::
  Threshold resolution which denotes that a bug has been resolved
  without being successfully fixed by developers. Resolutions above this
  threshold are considered to be resolved in an unsuccessful way.
  Default value is UNABLE_TO_REPRODUCE.
$g_bug_readonly_status_threshold $g_update_readonly_bug_threshold::
  Bug becomes readonly if its status is >=
  $g_bug_readonly_status_threshold. The bug becomes read/write again if
  re-opened and its status becomes less than this threshold. The default
  is RESOLVED. Once the bug becomes readonly, a user with an access
  level greater than or equal to $g_update_readonly_bug_threshold can
  still edit the bug.
$g_status_enum_workflow::
  'status_enum_workflow' defines the workflow, and reflects a simple
  2-dimensional matrix. For each existing status, you define which
  statuses you can go to from that status, e.g. from NEW_ you might list
  statuses '10:new,20:feedback,30:acknowledged' but not higher ones.The
  default is no workflow, where all states are accessible from any
  others.
$g_report_bug_threshold::
  This is the access level required to open a bug. The default is
  REPORTER.
$g_update_bug_threshold::
  This is the access level generally required to update the content of a
  bug. The default is UPDATER.
$g_handle_bug_threshold::
  This is the access level generally required to be access level needed
  to be listed in the assign to field. The default is DEVELOPER. If a
  more restrictive setting can be determined from
  $g_set_status_threshold, it will be used.
$g_update_bug_status_threshold $g_set_status_threshold::
  These settings control the access level required to promote a bug to a
  new status once the bug is opened.$g_set_status_threshold is an array
  indexed by the status value that allows a distinct setting for each
  status. It defaults to blank.If the appropriate status is not defined
  above, $g_update_bug_status_threshold is used instead. The default is
  DEVELOPER.
$g_bugnote_user_edit_threshold::
  Threshold at which a user can edit his/her own bugnotes. The default
  value is equal to the configuration setting
  $g_update_bugnote_threshold.
$g_bugnote_user_delete_threshold::
  Threshold at which a user can delete his/her own bugnotes. The default
  value is equal to the configuration setting
  $g_delete_bugnote_threshold.
$g_bugnote_user_change_view_state_threshold::
  Threshold at which a user can change the view status of his/her own
  bugnotes. The default value is equal to the configuration setting
  $g_change_view_status_threshold.
$g_allow_reporter_close::
  If set, the bug reporter is allowed to close their own bugs,
  regardless of their access level. The default is OFF.
$g_allow_reporter_reopen::
  If set, the bug reporter is allowed to reopen their own bugs once
  resolved, regardless of their access level. This allows the reporter
  to disagree with the resolution. The default is ON.
$g_allow_parent_of_unresolved_to_close::
  If set, no check is performed on the status of a bug's children, which
  allows the parent to be closed whether or not the children have been
  resolved. The default is OFF.

See also: link:#admin.customize.status[???]
