[[admin.about]]
== About MantisBT

[[admin.about.what]]
=== What is MantisBT?

MantisBT is a web based bug tracking system that was first made
available to the public in November 2000. Over time it has matured and
gained a lot of popularity, and now it has become one of the most
popular open source bug/issue tracking systems. MantisBT is developed in
PHP, with support for multiple database backends including
MySQL, PostgreSQL, Microsoft SQL Server and Oracle.

MantisBT can run on any operating system supported by PHP, provided that
the Database Extension for one of the above-mentioned RDBMS is installed.
It is known to run fine on Windows, Linux, macOS and a variety of Unix
operating systems.

[[admin.about.who]]
=== Who should read this manual?

This manual is targeted at the person responsible for evaluating,
installing and maintaining MantisBT.
Throughout this document, we typically refer to this person as the
_Administrator_.

[[admin.about.license]]
=== License

MantisBT is released under the terms of
https://www.gnu.org/copyleft/gpl.html[GNU General Public License (GPL)].
MantisBT is free to use and modify.
It is also free to redistribute as long as you abide by the
https://www.gnu.org/copyleft/gpl.html[GPL].

[[admin.about.download]]
=== How to get it?

MantisBT is available in several Linux distributions including: Debian,
Ubuntu, Fedora, Gentoo, Frugalware and others. Hence, if you are running
Linux, start by checking if your distribution has a package for
MantisBT. If not, or if the package is not up-to-date with the latest
MantisBT version, then you may want to download it directly from
https://mantisbt.org/download.php[here].

For Windows, macOS and other operating systems, use the link provided
above to download MantisBT. The download is compressed in tar.gz or zip
format. Both formats can be unpacked using tools like
https://www.7-zip.org/[7-Zip] (in case of Windows).

The following release types are available for download:

- The _latest_ production (stable) release;
- The _legacy_ release, which only receives fixes for security
  and critical bugs;
- _Nightly builds_ are generated from the latest development branches
  in our Git repository
- In the weeks preceding a new major version's go-live,
_Development_ releases (i.e. alpha, beta or release candidate)
are published;

CAUTION: Using development releases or nightly builds in production
is not recommended, unless the Administrator is familiar with PHP
and able to troubleshoot and fix any issues that may arise.

[[admin.about.name]]
=== About the Name

When initially seeking to name his project, Ken ran into a problem
that every programmer encounters: what is a good name? It has to be
descriptive, unique, and not too verbose. Additionally, having multiple
meanings would be a nice touch.

Names along the lines of PHP__something__ were quickly ruled out, as
-- Although popular -- these did not seem to be condoned by the PHP
Group developers.

Drawing inspiration from other Open Source projects like
Apache, Mozilla, Gnome and so forth, resulted in two eventual choices:
_Dragonfly_ and _Mantis_. The former was already the name of a webmail
package at the time, so in the end _Mantis_ was chosen.

https://en.wikipedia.org/wiki/Mantis[Praying Mantis] are very
elegant-looking insects that primarily feed on other insects and bugs.
They are extremely desirable in agriculture as they devour parasites
that feed on crops.

So, we have a name that is not only fairly distinctive, but also
descriptive in multiple ways.

The _BT_ suffix, which stands for _Bug Tracker_, was added to distinguish
this project from general usage of the word Mantis.
However, over time the project has typically been referred to as
just _Mantis_.

[[admin.about.history]]
=== History

Kenzaburo Ito and a friend originally created a bug tracker as an
internal tool for their pet project. A search for good, free packages
came up with nothing suitable, so they decided to create their own.

After a rewrite and cleanup, it was released to the public under the
GNU General Public License (GPL), which was chosen because he believed
that development tools should be cheap or free.

In 2002, Ken was joined by Jeroen Latour, Victor Boctor and Julian
Fitzell who formed the MantisBT's Core Development Team, initiating a
new era in the project's lifetime as is became a team endeavor.

[[admin.about.support]]
=== Support

There are plenty of resources to help answer support queries. Following
are the main ones:

* https://mantisbt.org/forums/[Forums] - The forums are one of the most
popular destinations for getting MantisBT support. Start off by
searching the forums for your question, and if not found then go ahead
and submit a new one.
* http://mantisbt.org/mailinglists.php[Mailing lists] - Several
lists are available, each of them with its own, specific purpose. Note
that posting messages is restricted to subscribers so you will have to
register before you can send messages; however, there are public
archives available if you're only interested in reading.
* https://gitter.im/mantisbt/mantisbt[Gitter] is a browser-based,
on-line chat that has mainly replaced the team's use of IRC. In the main
chat room, you can have a live discussion with the developers and other
MantisBT users. Gitter supports all modern browsers and also offers
Android and iOS-based clients, as well as an
https://irc.gitter.im/[IRC bridge].
* http://www.mantisbt.org/irc.php[IRC] - The `#mantisbt` IRC channel is
not very active anymore as the developers have moved on to using Gitter
for live discussions, but, the channel is still open.
There are many free IRC clients, such as
https://hexchat.github.io/[HexChat] or
https://www.icechat.net/[IceChat], amongst others.
You can also use Freenode's https://webchat.freenode.net/[Web Chat] to
connect to IRC via your web browser, which may also be useful when
you're behind a firewall that blocks the IRC port.
+
NOTE: IRC channel logs are archived and made
http://www.mantisbt.org/irclogs.php[available on the MantisBT web site].
* https://mantisbt.org/wiki/doku.php/mantisbt:start[Wiki] - The MantisBT
Wiki has information related to "How To (recipes)", FAQ, feature
requirements, plugins etc.
* Search - A good way for locating an answer to your question or finding
more information about a topic is to search across all MantisBT website
and the Internet via your favorite search engine, e.g.
https://www.google.com[Google] or https://www.bing.com[Bing].

[NOTE]
====
Support questions should not be sent directly to MantisBT developers or
through the MantisBT website's contact pages.

Also, our https://mantisbt.org/bugs/[bug tracker] is reserved for
reporting issues with the software, and *must not be used for support
requests*.
====

[[admin.about.news]]
=== MantisBT News

There are several ways to keep up to date with MantisBT news. These
include:

* We send release announcements and important updates to users
registered on our https://mantisbt.org/bugs[official bugtracker]. To get
onto our mailing list, users will have to signup there and verify their
email address. This same account can also be used to report, monitor,
and comment on issues relating to MantisBT.
* https://mantisbt.org/blog/[MantisBT Blog] is used to communicate
announcements about new releases, topics relating to MantisBT, etc.
Users are encouraged to subscribe to the RSS feed to know when new
articles are posted there.
* https://twitter.com/mantisbt[Twitter] is used to notify users about
important events related to MantisBT development.
Twitter users are encouraged to follow `@mantisbt`.

[[admin.about.versioning]]
=== Versioning

Our release numbering convention follows the guidelines of
https://semver.org/[Semantic Versioning]. Given a version number
_Major.Minor.Patch_ and an optional _Suffix_ (eg. 1.3.0-rc.1):

* Major - Indicates a very large change in the core package. Rewrites or
major milestones. API changes which are not backwards-compatible.
* Minor - Introduction of new features or significant changes in
functionality, in a backwards-compatible manner.
* Patch - Bug fixes, maintenance and security releases.
* Suffix - Optional, indicates a development release.
** a__N__ or alpha._N_ for alpha releases,
** b__N__ or beta._N_ for beta releases, or
** rc__N__ or rc._N_ for release candidates.
+
TIP: The absence of a suffix indicates a stable release.
