[[admin.about]]
== About MantisBT

[[admin.about.what]]
=== What is MantisBT?

MantisBT is a web based bug tracking system that was first made
available to the public in November 2000. Over time it has matured and
gained a lot of popularity, and now it has become one of the most
popular open source bug/issue tracking systems. MantisBT is developed in
PHP, with support to multiple database backends including MySQL, MS SQL
and PostgreSQL.

MantisBT, as a PHP script, can run on any operating system that is
supported by PHP and has support for one of the DBMSes that are
supported. MantisBT is known to run fine on Windows, Linux, macOS and a
variety of Unix operating systems.

[[admin.about.who]]
=== Who should read this manual?

This manual is targeted for the person responsible for evaluating,
installing and maintaining MantisBT in a company. Typically we refer to
this person as the MantisBT administrator.

[[admin.about.license]]
=== License

MantisBT is released under the terms of
https://www.gnu.org/copyleft/gpl.html[GNU General Public License (GPL)].
MantisBT is free to use and modify. It is free to redistribute as long
as you abide by the distribution terms of the
https://www.gnu.org/copyleft/gpl.html[GPL].

[[admin.about.download]]
=== How to get it?

MantisBT is available in several Linux distributions including: Debian,
Ubuntu, Fedora, Gentoo, Frugalware and others. Hence, if you are running
Linux, start by checking if your distribution has a package for
MantisBT. If not, or if the package is not up-to-date with the latest
MantisBT version, then you may want to download it directly from
https://mantisbt.org/download.php[here].

For Windows, macOS and other operating systems, use the link provided
above to download MantisBT. The download is compressed in tar.gz or zip
format. Both formats can be unpacked using tools like
https://www.7-zip.org/[7-Zip] (in case of Windows).

Note that at any point in time there are typically two "latest" MantisBT
releases that are available for download. The latest production release
(stable), and the latest development release which can be an alpha or a
release candidate. It is not recommended to use development releases in
production specially if it is still in the alpha stage unless the
administrator is familiar with PHP and is able to troubleshoot and fix
any issues that may arise.

[[admin.about.name]]
=== About the Name

When initially seeking to name this project Ken ran into a problem every
programmer encounters. What is a good name? It has to be descriptive,
unique, and not too verbose. Additionally having multiple meanings would
be a nice touch. Quickly ruled out were php*Something* names which,
incidentally, although popular, do not seem to be condoned by the PHP
Group developers. Drawing inspiration from Open Source projects like
Apache, Mozilla, Gnome, and so forth resulted in two eventual choices:
Dragonfly and Mantis. Dragonfly was already the name of a webmail
package. So the name became Mantis.

Praying Mantis are insects that feed primarily on other insects and
bugs. They are extremely desirable in agriculture as they devour insects
that feed on crops. They are also extremely elegant looking creatures.
So, we have a name that is fairly distinctive and descriptive in
multiple ways. The BT suffix stands for "Bug Tracker" and distinguishes
this project from general usage of the word Mantis. However, over time
the project was typically referred to as Mantis.

[[admin.about.history]]
=== History

Kenzaburo Ito and a friend originally created a bug tracker as an
internal tool for their pet project. A search for good, free packages
came up with nothing suitable so they wrote their own. After a rewrite
and cleanup it was made available to the public via the GNU General
Public License (GPL). The GPL was chosen partly because of his belief
that development tools should be cheap or free. In 2002, Ken was joined
by Jeroen Latour, Victor Boctor and Julian Fitzell to be the
administrators and the core development team of MantisBT. This marks a
new era in MantisBT lifetime where it is now a team project.

[[admin.about.support]]
=== Support

There are plenty of resources to help answer support queries. Following
are the main ones:

* https://mantisbt.org/forums/[Forums] - The forums are one of the most
popular destinations for getting MantisBT support. Start off by
searching the forums for your questions, if not found, then go ahead and
submit a question.
* http://www.mantisbt.org/mailinglists.php[Mailing lists] - Several
lists are available, each of them with its own, specific purpose. Note
that posting messages is restricted to subscribers so you will have to
register before you can send messages; however, there are public
archives available if you're only interested in reading.
* https://gitter.im/mantisbt/mantisbt[Gitter] is a browser-based,
on-line chat that has mainly replaced the team's use of IRC. In the main
chat room, you can have a live discussion with the developers and other
MantisBT users. Gitter supports all modern browsers and also offers
Android and iOS-based clients, as well as an https://irc.gitter.im/[IRC
bridge].
* http://www.mantisbt.org/irc.php[IRC] - The IRC channel not very active
anymore, as the developers have moved on to using Gitter for live
discussions; nevertheless, the channel is still open. There are many
free IRC clients: XChat (for Linux), http://hexchat.github.io/[HexChat],
http://www.icechat.net/[IceChat] amongst others. You can also use
http://webchat.freenode.net/[Web Chat] to connect to IRC via your web
browser, which may also be useful when you're behind a firewall that
blocks the IRC port. The IRC channel logs are archived and made
http://www.mantisbt.org/irclogs.php[available on the MantisBT web site].
* https://mantisbt.org/wiki/doku.php/mantisbt:start[Wiki] - The MantisBT
Wiki has information related to "How To (recipes)", FAQ, feature
requirements, plugins etc.
* Search - A good way for locating an answer to your question or finding
more information about a topic is to search across all MantisBT website
and the Internet via your favorite search engine, e.g.
https://www.google.com[Google] or https://www.bing.com[Bing].

[NOTE]
====
Support questions should not be sent directly to MantisBT developers or
through the MantisBT website's contact pages.

Also, our https://mantisbt.org/bugs/[bug tracker] is reserved for
reporting issues with the software, and _must not be used for support
requests_.
====

[[admin.about.news]]
=== MantisBT News

There are several ways to keep up to date with MantisBT news. These
include:

* We send release announcements and important updates to users
registered on our https://mantisbt.org/bugs[official bugtracker]. To get
onto our mailing list, users will have to signup there and verify their
email address. This same account can also be used to report, monitor,
and comment on issues relating to MantisBT.
* https://mantisbt.org/blog/[MantisBT Blog] is used to communicate
announcements about new releases, topics relating to MantisBT, etc.
Users are encouraged to subscribe to the RSS feed to know when new posts
are posted there.
* https://twitter.com/mantisbt[Twitter] is used to notify users about
up-to-date details about what is happening with MantisBT development.
Twitter users are encouraged to follow "@mantisbt".

[[admin.about.versioning]]
=== Versioning

Our release numbering convention follows the guidelines of
https://semver.org/[Semantic Versioning]. Given a version number
_Major.Minor.Patch_ and an optional _Suffix_ (eg. 1.3.0-rc.1):

* Major - Indicates a very large change in the core package. Rewrites or
major milestones. API changes which are not backwards-compatible.
* Minor - Introduction of new features or significant changes in
functionality, in a backwards-compatible manner.
* Patch - Bug fixes, maintenance and security releases.
* Suffix - Optional, indicates a development release.
** a__N__ or alpha._N_ for alpha releases,
** b__N__ or beta._N_ for beta releases, or
** rc__N__ or rc._N_ for release candidates.
+
Absence of suffix indicates a stable release.
