= Admin Guide : Reference for MantisBT 2.x Administrators
MantisBT Development Team <https://mantisbt.org>; Damien Regad
:revnumber: 2.25.0
:revdate: 12-Aug-2020
:revremark: 3rd edition
:doctype: book
:sectnums:
:xrefstyle: full
:toc: left
:toclevels: 3
:logo:  ../../images/mantis_logo.png
:icons: font
:title-logo-image: {logo}
:source-highlighter: rouge
// Disabling default language, see https://github.com/asciidoctor/asciidoctor/issues/3734
//:source-language: php
:source-linenums-option:
:tabsize: 4

ifdef::backend-html5[]
image::{logo}[MantisBT logo,align="center"]
endif::[]

[abstract]
.Abstract
This book is targeted at MantisBT administrators, and documents the
installation, upgrade, configuration, customization and administration
tasks required to operate the software.


[colophon]
== Colophon

{doctitle} {version-label} {revnumber} from {revdate}.

This document was written by the {author},
with contributions from the MantisBT community.

{revremark} was converted to AsciiDoc from the previous DocBook version
by {author_2}.

*Legal Notice*

Copyright © 2020 {author}.

Permission is granted to copy, distribute and/or modify this document
under the terms of the
https://www.gnu.org/licenses/fdl.html[GNU Free Documentation License],
Version 1.3 or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

Code samples are released under the terms of the
https://www.gnu.org/licenses/old-licenses/gpl-2.0.html[GNU General Public License],
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.


// Individual book chapters are maintained in separate files

include::About.adoc[]

include::Installation.adoc[]

include::User_Management.adoc[]

include::Workflow.adoc[]

include::Configuration.adoc[]

include::Page_Descriptions.adoc[]

include::Customizing.adoc[]

include::Authentication.adoc[]

include::Troubleshooting.adoc[]

include::Project_Management.adoc[]

include::Contributing.adoc[]

include::Revision_History.adoc[]
