[[admin.install]]
== Installation

This chapter explains how to install or upgrade MantisBT.

[[admin.install.overview]]
=== Overview

The table below contains a high-level overview of the processes. Refer
to the corresponding sections for details.

[cols=",",options="header",]
|===
|New Installation |Upgrade
a|
[arabic]
. <<admin.install.requirements>>
. <<admin.install.preinstall>>
. <<admin.install.new>>
. <<admin.install.config>>
. <<admin.install.postcommon>>
. <<admin.install.postinstall>>

a|
[arabic]
. <<admin.install.preinstall>>
. <<admin.install.backups>>
. Put the site down for maintenance
. <<admin.install.upgrade>>
. <<admin.install.postcommon>>
. <<admin.install.postupgrade>>

|===

[[admin.install.requirements]]
=== System Requirements

[[admin.install.requirements.hardware]]
==== Server Hardware Requirements

MantisBT has modest hardware requirements. It requires a computer that
is able to run the server software (see
<<admin.install.requirements.software>>).

Server type::
The server can be a shared public web server or a dedicated co-located
box.

CPU and Memory::
As for any web application, you should size your server based on the
traffic on the site.
* Disk
+
The application code is less than 50 MiB.
+
The amount of disk space required for the database will vary depending
on the RDBMS and the volume of data, the main driving factor being the
expected number and size of attachments.

[[admin.install.requirements.software]]
==== Server Software Requirements

All of the required software is open source and free for both commercial
and non-commercial use.
Please refer to <<admin.install.requirements.compat_table>>
below for details about minimum and recommended versions.

Operating System::
MantisBT runs on Windows, macOS, Linux, Solaris, the BSDs, and just
about anything that supports the required server software.

Web Server::
MantisBT is mainly tested with
https://docs.microsoft.com/en-us/iis[Microsoft IIS] and
https://www.apache.org/[Apache]. However, it is expected to work with
any recent web server software.
+
File Extensions:::
MantisBT uses only _.php_ files.
+
If your webserver is configured for other extensions (e.g. .php,
.phtml) then you will have to add support for .php files; this should
be a trivial modification.
Further details can be found in the
https://www.php.net/manual/en/install.php[PHP documentation].

PHP::
The web server must support https://www.php.net/[PHP],
which can be installed as CGI or any other integration technology.
+
MantisBT is designed to work in as many environments as possible.
Consequently, only a minimal set of extensions are required, and
others are optional, affecting only one feature.
+
[[admin.install.requirements.software.phpext]]
Mandatory extensions:::
  * The _database extension_ for the RDBMS being used (i.e.
https://www.php.net/manual/en/book.mysqli.php[mysqli],
https://www.php.net/manual/en/book.pgsql.php[pgsql],
https://www.php.net/manual/en/book.oci8.php[oci8],
https://www.php.net/manual/en/book.sqlsrv.php[sqlsrv]).
  * _mbstring_ -- Required for Unicode (UTF-8) support.
  * _date, hash, json, pcre, Reflection, session_ -- 
Required to run MantisBT in general.

Optional extensions:::

  * _Curl_ -- required for the Twitter integration feature
  * _GD_ -- required for the captcha feature
  * _Fileinfo_ -- Required for file attachments and most of the plugins
+
WARNING: Without this extension, file previews and downloads do not work
properly, as MantisBT is not able to send the _Content-Type_ header
to the browser requesting the attachment.

  * _LDAP_ -- required for LDAP or Active Directory authentication
(see <<admin.auth.ldap>>).

Database::
MantisBT requires a database to store its data.
+
[TIP]
====
The MantisBT development team mainly works with MySQL.
Consequently, testing for other database platforms is not as extensive,
and we mainly rely on community contributions to improve support and
fix issues.

We therefore recommend to use MySQL with MantisBT.
====
+
The supported RDBMS are:
+
  * MySQL (or one of its forks, e.g. MariaDB)
  * PostgreSQL
+
Experimental support is also available for:
+
  * Microsoft SQL Server
  * Oracle
+
[CAUTION]
====
Experimental platforms may require manual intervention by a skilled
Database Administrator to complete the installation, and there may be
known issues or limitations when using MantisBT with them.

Please refer to our https://mantisbt.org/bugs/[Issue tracker],
filtering on categories _db mssql_ and _db oracle_ to find out more
about such issues.
====

[[admin.install.requirements.software.versions]]
===== Versions compatibility table

Our minimum requirements are generally based on availability of support
for the underlying software by their respective vendors. In some cases,
we do require a specific version because we rely on a feature that is
not available in older releases.

[[admin.install.requirements.compat_table]]
.Versions compatibility
[cols="5*",options="header",stripes=even]
|===
|Category |Package |Minimum Version |Recommended |Comments

.5+|RDBMS |MySQL |5.5.35 |5.6 or later |PHP extension: mysqli
|MariaDB |5.5.35 |10.x or later |PHP extension: mysqli
|PostgreSQL |9.2 |9.2 or later |PHP extension: pgsql
|MS SQL Server |2012 |2012 or later |PHP extension: sqlsrv
|Oracle |11gR2 |11gR2 or later |PHP extension: oci8

|PHP |PHP |5.5.x |7.2 or later |
  See <<admin.install.requirements.software.phpext,PHP extensions>>

.4+|Web Server |Apache |2.2.x |2.4.x |
|lighttpd |1.4.x |1.4.x |
|nginx |1.10.x |1.16.x or later |
|IIS |7.5 |8.0 |Windows Server 2008 R2 SP1 or later |
|===

[WARNING]
====
Running MantisBT with versions of the software components lower than the
minimum requirements listed above is not supported.
====

[[admin.install.requirements.client]]
==== Client Requirements

MantisBT should run on all recent browsers in the market, including but
not limited to:

* Firefox
* Internet Explorer 11
* Edge
* Chrome
* Safari
* Opera

[[admin.install.preinstall]]
=== Pre-installation / upgrade tasks

These tasks cover the download and deployment of MantisBT, and should be
performed prior to any new installation or upgrade.

[arabic]
. Download MantisBT (see <<admin.about.download>>)
. Verify the downloaded file’s integrity by checking the corresponding
ASCII-armored signature file against the
https://github.com/mantisbt/mantisbt/blob/master/KEYS.md[official list of PGP keys]
used by the MantisBT developers to sign the release packages.
. Transfer the downloaded file to your webserver
+
This can be done using whatever method you like best (ftp, scp, etc).
You will need to telnet/ssh into the server machine for the next steps.
. Extract the release
+
TIP: It is highly recommended to maintain a separate directory for each
release. This not only avoids mismatch between versions (files may have
been added or removed), but also provides an easy path to downgrade your
installation, should you need to.
+
The usual command is (1 step):
+
....
tar -xzf filename.tar.gz
....
+
OR (2 steps):
+
....
gunzip filename.tar.gz
tar -xf filename.tar
....
+
Other file archiving tools such as https://www.7-zip.org/[7-Zip] should
also be able to handle decompression of the archive.
+
The extraction process should create a new directory like
_mantisbt-2.24.1_
. Rename the directory
+
For new installations, you may want to rename the directory just created
to something simpler, e.g. _mantisbt_
+
....
mv mantisbt-2.24.1 mantisbt
....

[[admin.install.new]]
=== New Installation

This chapter explains how to perform a new installation of MantisBT.

Start by checking <<admin.install.requirements>>
and installing the appropriate version of required software.

Once that is done, execute the installation script. From your web
browser, access

....
http://yoursite/mantisbt/admin/install.php
....

The installation procedure will go through the following steps:

[arabic]
. Check basic parameters for the web server
. Collect required information for the installation
* database type
* database server hostname
* database user and password (schema owner account)
+
Required privileges: SELECT, INSERT, UPDATE, and DELETE

* high-privileged database account
+
Additional privileges required: INDEX, CREATE, ALTER, and DROP
+
If this account is not specified, the database user will be used.

* database table prefix, suffix and plugin table prefix
* default time zone

+
The installer can optionally generate a SQL script instead of
directly executing the statements. This may be useful for debugging
purposes, or in environments where a manual creation of the schema
is required.
+
[WARNING]
====
*Executing this script may not result in a fully functional database*,
particularly in upgrade scenarios.

This is due to the fact that some upgrade steps require the execution
of PHP code which cannot be translated to SQL statements.

Use at your own risk.
====

+
When all the required information has been entered,
click the _Install/Upgrade Database_ button.
The script will create the database and tables.


. The default Administrator user account is created at this stage, to
allow the initial login and setup of MantisBT.

. The script then attempts to write a basic `config_inc.php` file to store
the database connection parameters.
+
NOTE: This operation will fail if the web server's user account
does not have write permissions to the `config` directory
(which is recommended for obvious security reasons).
In this case, you will have to manually create the file and copy/paste
the contents from the page.

. Finally, the script perform post-installation checks on the system.
+
Review and correct any errors.

[[admin.install.upgrade]]
=== Upgrading

This chapter explains how to upgrade an existing MantisBT installation.

Start by Performing the steps described in
<<admin.install.preinstall>> above.

[arabic]
. Put the site down for maintenance
+
....
cp mantis_offline.php.sample mantis_offline.php
....
+
This will prevent users from using the system while the upgrade is in
progress.
. Always *Backup your code, data and config files* before upgrading !
+
This includes your Mantis directory, your attachments, and your
database. Refer to <<admin.install.backups>> for details.
. Copy the configuration files
+
To preserve your system settings, you should copy the files listed below
to subdirectory `config` of the new installation.

* `config_inc.php`,
* `custom_strings_inc.php`,
* `custom_constants_inc.php` and
* `custom_functions_inc.php`.
+
[NOTE]
====
The above list is not exhaustive. You might also have to copy other
custom files specific to your installation such as logo, favicon, css,
etc.
====
. Copy third-party plugins
+
To maintain system functionality, you should copy any additional plugins
installed in the `plugins` subdirectory.
+
For example on Unix, you could use the following command; it will copy
all installed plugins (in local subdirectories or symlinked), excluding
bundled ones.
+
[source,shell script]
....
cd /path/to/mantisbt/plugins
find -maxdepth 1 ! -path . -type d -o -type l |
    grep -Pv "(Gravatar|MantisCoreFormatting|MantisGraph|XmlImportExport)" |
    xargs -Idirs cp -r dirs /path/to/mantisbt-NEW/plugins
....
+
[WARNING]
====
Make sure that you *do not overwrite any of the bundled plugins* as per
the list below, with an older version.

* Avatars via Gravatar (`Gravatar`)
* MantisBT Formatting (`MantisCoreFormatting`)
* Mantis Graphs (`MantisGraph`)
* Import/Export issues (`XmlImportExport`)
====
. Execute the upgrade script. From your web browser, access
+
....
http://yoursite/mantisbt-NEW/admin/install.php
....
+
where _mantisbt-NEW_ is the name of the directory where the new release
was extracted
. Provide required information for the upgrade
* high-privileged database account
+
Additional privileges required: INDEX, CREATE, ALTER, and DROP
+
If this account is not specified, the database user will be used.
. Click the _Install/Upgrade Database_ button
. At the end of the upgrade, review and correct any warnings or errors.

[NOTE]
.Upgrading large databases
====
When processing large databases from versions older than 1.2, the
upgrade script may fail during the conversion of date fields due to
execution timeout, leaving the system in an inconsistent
(i.e. partially updated) state.

In this case, you should simply restart the upgrade process, which will
resume where it left off. Note that you may have to repeat this several
times, until normal completion.

Reference: MantisBT
https://mantisbt.org/bugs/view.php?id=12735[issue #12735].
====

[[admin.install.config]]
=== Configure your installation

There are many settings that you can adjust to configure and customize
MantisBT. Refer to <<admin.config>>, as well as the
`config_defaults_inc.php` file for in depth explanations of the
available options. Also check out <<admin.customize>> for further
options to personalize your installation.

This step is normally only required for new installations, but when
upgrading you may want to review and possibly customize any new
configuration options.

Open or create the `config_inc.php` file in subfolder `config` in an
editor and add or modify any values as required. These will override the
default values.

You may want to use the provided `config_inc.php.sample` file as a
starting point.

[WARNING]
====
You should *never edit the `config_defaults_inc.php` file* directly,
as this could cause issues with future upgrades. Always store custom
configuration in your own `config_inc.php` file.
====

[WARNING]
====
The MantisBT configuration files (`config_inc.php` as well as
`custom_strings_inc.php`, `custom_constants_inc.php`,
`custom_functions_inc.php`, etc.) should always be saved as
https://www.w3.org/International/questions/qa-byte-order-mark[_UTF-8 without BOM_].
Failure to do so may lead to unexpected display issues.
====

[[admin.install.postcommon]]
=== Post-installation and upgrade tasks

Instructions in this section are common to both new installations and
upgrades, and should be applied after completing either process.

[arabic]
. Test your configuration
+
Navigate to http://yoursite-NEW/mantisbt/admin/check/index.php
to validate whether everything is setup correctly,
and take corrective action as needed.

. Delete the _admin_ folder
+
Once you have confirmed that the install or upgrade process was
successful, you should delete this directory
+
....
rm -r admin
....
+
For security reasons, the scripts within this directory should not be
freely accessible on a live MantisBT site, particularly one which is
accessible via the Internet, as they can allow unauthorized people (e.g.
hackers) to gain technical knowledge about the system, as well as
perform administrative tasks.
+
[WARNING]
====
Omitting this important step will leave your MantisBT instance exposed
to several potentially severe attacks, e.g.
https://mantisbt.org/bugs/view.php?id=23173[issue #23173] (if
https://www.php.net/manual/en/mysqli.configuration.php#ini.mysqli.allow-local-infile[mysqli.allow_local_infile]
is enabled in php.ini).
====

[[admin.install.postinstall]]
=== Post-installation tasks

Instructions in this section should only be applied after a new
installation

[arabic]
. Navigate to http://yoursite/mantisbt and login to your bugtracker
+
Use the default Administrator account. The id and password are
_administrator / root_.
. Create a new Administrator account
+
Go to _Manage > Manage Users_ and create a new account with
'administrator' access level.
. Disable or delete the default Administrator account
. Create a new Project
+
Go to _Manage > Manage Projects_ and create a new project

[[admin.install.postupgrade]]
=== Post-upgrade tasks

Instructions in this section should only be applied after upgrading an
existing installation.

[arabic]
. Test the new release
+
Perform any additional testing as appropriate to ensure the new version
does not introduce any regressions.
Upgrade third-party plugins as needed.
. Switch the site to the new version
+
The commands below should be executed from the web root (or wherever the
MantisBT scripts are installed) and assume that the "live" directory
(old version) is named _mantisbt_ and the new release directory is
_mantisbt-NEW_.
+
....
mv mantisbt mantisbt-OLD
mv mantisbt-NEW mantisbt
....

. Put the site back on line
+
....
rm mantis_offline.php
....
+
This should be the final step in the upgrade process, as it will let
users login again.

. Remove or disable access to the old directory
+
....
rm -r mantisbt-OLD
....

[[admin.install.backups]]
=== Backups

It is strongly recommended to backup your MantisBT database on a regular
basis. The method to perform this operation depends on which RDBMS you
use.

Backups are a complex subject, and the specificities of implementing and
handling them for each RDBMS are beyond the scope of this document. For
your convenience, the section below provides a simple method to backup
MySQL databases.

You should also consider implementing backups of your MantisBT code
(which includes your configs and possibly customization), as well as
issue attachments (if stored on disk) and project documents.

[WARNING]
====
You should always backup your system (code and database) before
upgrading !
====

[[admin.install.backups.mysql]]
==== MySQL Backups

MySQL databases are easy to backup using the
https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html[_mysqldump_]
command:

....
mysqldump -u<username> -p<password> <database name> > <output file>
....

To restore a backup you will need to have a clean database. Then run:

....
mysql -u<username> -p<password> <database name> < <input file>
....

You can also perform both of these tasks using
http://www.phpmyadmin.net/[phpMyAdmin]

A good idea is to make a backup script and run it regularly through cron
or a task scheduler (for Windows see http://www.wincron.com/[WinCron] ).
Using the current date in the filename can prevent overwriting and make
cataloguing easier.

References and useful links:

* http://dev.mysql.com/doc/refman/5.1/en/mysqlhotcopy.html[mysqlhotcopy
documentation]
* http://sourceforge.net/projects/automysqlbackup/[automysqlbackup
script]

[[admin.install.uninstall]]
=== Uninstall

It is recommended that you make a complete backup of your MantisBT data
before uninstalling, in case you wish to access it in the future.
See <<admin.install.backups>> for details.

To uninstall MantisBT:

* Delete the MantisBT directory and all files and subdirectories.

* Drop all MantisBT tables from the database, these can be identified by
the configured prefix for the installation. The default prefix is
`mantis`.
+
If your MantisBT database does not contain any other data and you have
the permissions to do so, you can simply drop the whole database.

* Remove any customizations or additions that you may have made.
